
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 20 13:56:28 CST 2026
//----------------------------------------------------

package AnalizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIGUAL = 31;
  public static final int MULT = 25;
  public static final int MEIGUAL = 30;
  public static final int PARENIZQ = 20;
  public static final int LLAVEDER = 19;
  public static final int INT = 2;
  public static final int INTNUM = 15;
  public static final int FOR = 8;
  public static final int WRITE = 13;
  public static final int NOIGUAL = 33;
  public static final int NOT = 34;
  public static final int ESIGUAL = 32;
  public static final int IGUAL = 27;
  public static final int BOOL = 5;
  public static final int DIV = 26;
  public static final int IF = 6;
  public static final int ID = 14;
  public static final int EOF = 0;
  public static final int TRUE = 10;
  public static final int STRINGWORD = 17;
  public static final int error = 1;
  public static final int FLOATNUM = 16;
  public static final int NEWLINE = 35;
  public static final int MENOR = 28;
  public static final int PARENDER = 21;
  public static final int MAYOR = 29;
  public static final int REST = 24;
  public static final int ELSE = 7;
  public static final int READ = 12;
  public static final int WHILE = 9;
  public static final int LLAVEIZQ = 18;
  public static final int FLOAT = 3;
  public static final int SUM = 23;
  public static final int STRING = 4;
  public static final int FALSE = 11;
  public static final int PYC = 22;
}

